# Copyright (c) 2016-2021 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

name: Build docs
on:
  push:
    branches:
      - master

env:
  PYTHON_VERSION: 3.x
  EM_VERSION: 2.0.4
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build documentation
    concurrency: docs-build-and-deploy
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          #python-version: ${{ env.PYTHON_VERSION }}
      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          # Cache the Python package environment, excluding pip and setuptools installed by setup-python
          path: |
            ~/.cache/pip
            ${{ env.pythonLocation }}/bin/*
            ${{ env.pythonLocation }}/include
            ${{ env.pythonLocation }}/lib/python*/site-packages/*
            !${{ env.pythonLocation }}/bin/pip*
            !${{ env.pythonLocation }}/lib/python*/site-packages/pip*
            !${{ env.pythonLocation }}/lib/python*/site-packages/setuptools*
          key: ${{ env.pythonLocation }}-${{ hashFiles('docs/requirements.txt') }}
      
      - name: Install Python dependencies
        run: |
          pip install \
            mkdocs\
            mkdocs-material\
            mkdocs-minify-plugin>=0.3 \
            mkdocs-redirects>=1.0 \
            mkdocs-rss-plugin>=0.17

      - name: Setup Emscripten cache
        id: cache-system-libraries
        uses: actions/cache@v2
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
      - uses: mymindstorm/setup-emsdk@v9
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
        
      - name: mkdocs-materia
        run: |
          ls
          mkdocs build
          ls site
          git clone https://${{secrets.CODING_USERNAME}}:${{secrets.CODING_PASSWD}}@github.com/100askTeam/Docs-DongshanPi.git  --branch main --single-branch main
          cp -rfd site/* main/
          cd main
          ls
          git config --local user.email "team100ask@outlook.com"
          git config --local user.name "100askTeam"
          git add .
          git commit -m "Update documentation" -a || true
          git push origin main
          
